"""add fk indexes

Revision ID: 0bbb9907e9a6
Revises: 57848c4b67db
Create Date: 2026-08-08 12:15:49.677547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbb9907e9a6'
down_revision: Union[str, None] = '57848c4b67db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comparisons_release_id'), 'comparisons', ['release_id'], unique=False)
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environments_release_id'), 'environments', ['release_id'], unique=False)
    op.create_index(op.f('ix_regressions_comparison_id'), 'regressions', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_releases_project_id'), 'releases', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_test_runs_environment_id'), 'test_runs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_test_runs_release_id'), 'test_runs', ['release_id'], unique=False)
    op.create_index(op.f('ix_test_runs_workflow_id'), 'test_runs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_index(op.f('ix_test_runs_workflow_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_release_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_environment_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_releases_project_id'), table_name='releases')
    op.drop_index(op.f('ix_regressions_comparison_id'), table_name='regressions')
    op.drop_index(op.f('ix_environments_release_id'), table_name='environments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_index(op.f('ix_comparisons_release_id'), table_name='comparisons')
    # ### end Alembic commands ###
