"""add_deployment_timestamps

Revision ID: 25ecd1d919ec
Revises: e659649a6013
Create Date: 2026-08-09 18:13:57.469436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ecd1d919ec'
down_revision: Union[str, None] = 'e659649a6013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deployments', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'finished_at')
    op.drop_column('deployments', 'started_at')
    # ### end Alembic commands ###
