"""add environment zerops_service_stack_id for cleanup

Revision ID: 76fd3808012c
Revises: c934670b1926
Create Date: 2026-08-08 15:42:01.942120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fd3808012c'
down_revision: Union[str, None] = 'c934670b1926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('zerops_service_stack_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'zerops_service_stack_id')
    # ### end Alembic commands ###
