"""add_environment_auto_teardown_at

Revision ID: 9f47aee12277
Revises: f28d4c6a1e9b
Create Date: 2026-08-09 16:23:42.205876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f47aee12277'
down_revision: Union[str, None] = 'f28d4c6a1e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('auto_teardown_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'auto_teardown_at')
    # ### end Alembic commands ###
