"""add project zerops_runtime

Revision ID: c934670b1926
Revises: df003fac57df
Create Date: 2026-08-08 15:26:59.527212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c934670b1926'
down_revision: Union[str, None] = 'df003fac57df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('zerops_runtime', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'zerops_runtime')
    # ### end Alembic commands ###
