"""replace project production_version with production_branch, add github_token

Revision ID: df003fac57df
Revises: ccc55aee9c1c
Create Date: 2026-08-08 14:41:24.554304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df003fac57df'
down_revision: Union[str, None] = 'ccc55aee9c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('production_branch', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('production_commit_sha', sa.String(length=64), nullable=False))
    op.add_column('projects', sa.Column('github_token', sa.String(length=255), nullable=True))
    op.drop_column('projects', 'production_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('production_version', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('projects', 'github_token')
    op.drop_column('projects', 'production_commit_sha')
    op.drop_column('projects', 'production_branch')
    # ### end Alembic commands ###
