"""add_project_root_directory

Revision ID: e659649a6013
Revises: 9f47aee12277
Create Date: 2026-08-09 17:26:39.305794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e659649a6013'
down_revision: Union[str, None] = '9f47aee12277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('root_directory', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'root_directory')
    # ### end Alembic commands ###
